version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - nilerr
    - errorlint
    - bodyclose
    - noctx
    - prealloc
    - unconvert
    - unparam
    - whitespace
    - varnamelen
    - nlreturn
    - revive
    - intrange
    - testifylint
    - protogetter
    - dupword
    - thelper
    - wsl_v5
    - usestdlibvars
    - makezero
    - wastedassign
    - perfsprint
    - gosec

  settings:
    wsl_v5:
      disable:
        - decl
    gosec:
      excludes:
        - G115
    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks:
        - ifElseChain
        - whyNoLint

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    errorlint:
      asserts: false

    varnamelen:
      min-name-length: 3
      ignore-names:
        - id
        - ok
        - tx
        - wg
        - mu
        - ch
        - to
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
        - r http.Request
        - lc fx.Lifecycle
        - i int
        - j int
        - n int
        - t testing.T
        - b testing.B

    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

  exclusions:
    generated: strict
    paths:
      - front
      - proto
      - third_party
      - node_modules
    rules:
      - path: "gen\\."
        linters: [unused, unparam, gocritic, whitespace, staticcheck, govet, unconvert, varnamelen, revive, wsl_v5, gosec, perfsprint]

formatters:
  enable:
    - gofmt
    - goimports

  exclusions:
    generated: strict
    paths:
      - front
      - proto
      - third_party
      - node_modules
